version: "2"
services:
  mqtt:
    image: ashleywm/mosquitto-dns-cerbot
    networks:
      - net
    ports:
      - 8083:8083
      - 8883:8883
    environment:
      - DOMAIN=mqtt.myserver.com
      - EMAIL=me@myserver.com
    volumes:
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
      - ./secrets:/secrets
    container_name: mqtt
    restart: always
networks:
  net:
    external:
      name: net
